### ISSUE TITLE
Артефакт

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-38-React-tasks-app-with-server#1]
https://github.com/BohdanLuts/home-work-lesson-38-React-tasks-app-with-server/blob/e60d694481a87deaccc98bd88db81f484529c8a4/src/components/forms/TaskForm/index.jsx#L11
- копіпаста може зіграти злий жарт)

**Comment by BohdanLuts** [comment]
Виправлено: isBought замінено на isDone.
