### ISSUE TITLE
Тип action

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-38-React-tasks-app-with-server#2]
https://github.com/BohdanLuts/home-work-lesson-38-React-tasks-app-with-server/blob/e60d694481a87deaccc98bd88db81f484529c8a4/src/store/slices/tasksSlice.js#L7
- тут, як і далі, варто використати оголошену вище TASKS_SLICE_NAME

**Comment by BohdanLuts** [comment]
Виправлено!
